---
- name: Hello World
  hosts: all
  sources:
    - name: dynatrace Saas
      dynatrace.event_driven_ansible.dt_esa_api:
        dt_api_host: "https://abc.live.dynatrace.com"
        dt_api_token: "asjfsjkfjfjh"
        delay: 60
  rules:
    - name: Dynatrace
      condition: event.title == "No process found for rule httpd-alert"
      actions:
        - debug:
